In [94]:
using LaTeXStrings

In [126]:
a=-1
b= 1
remap(x,a,b) = ((1-x).*a + (1+x).*b)/2

ξ(x,a,b) = (2*x - (a+b))/(b-a)

ξ (generic function with 1 method)

In [128]:
ξ(10,-1,1)

10.0

In [140]:
ϕ = zeros(2,Ndof) 

ϕ[1,1] = 1
ϕ[end,end] = 1
ϕ

2x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0

In [141]:
zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [125]:
remap(,a,b)

100.0

In [6]:
Nel = 3
dof_map = zeros(Int, 2, Nel)
for i = 1:Nel
  dof_map[1,i] = i
  dof_map[2,i] = i+1
end
dof_map

2x3 Array{Int64,2}:
 1  2  3
 2  3  4

In [118]:
Ndof = Nel + 1
for e = 1:Nel
    #dMe = dmass_matrix(xn[e], xn[e+1])
    for i = 1:2
        ig = dof_map[i,e]
        for k = 1:2
            kg = dof_map[k,e]
            #dM[kg,ig] += dMe[k,i]
            println("phig[$kg,$ig] += phi$e[$k,$i]")
        end
    end
end

phig[1,1] += phi1[1,1]
phig[2,1] += phi1[2,1]
phig[1,2] += phi1[1,2]
phig[2,2] += phi1[2,2]
phig[2,2] += phi2[1,1]
phig[3,2] += phi2[2,1]
phig[2,3] += phi2[1,2]
phig[3,3] += phi2[2,2]
phig[3,3] += phi3[1,1]
phig[4,3] += phi3[2,1]
phig[3,4] += phi3[1,2]
phig[4,4] += phi3[2,2]


In [87]:
i = 2
for i in 1:10
    println(latexstring("$ \alpha + 2 $"))
end

LoadError: LoadError: syntax: invalid interpolation syntax: "$ "
while loading In[87], in expression starting on line 3

In [109]:
latexstring("an equation: \$1 + \\phi_$i^2\$")

L"an equation: $1 + \phi_2^2$"